#!/usr/bin/env bash

# Homebrew
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Haskell
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Php
export PATH="$HOME/.composer/vendor/bin:$PATH"

# Golang
export PATH="$GOPATH/bin:$PATH"

# TeX
export PATH="/usr/local/opt/texinfo/bin:$PATH"
