#!/usr/bin/env bash

export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
