#export TERM=xterm-256color

# Locale
export LC_ALL=en_US.UTF-8

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin:~/.scripts:~/bin

# Configure X
xsetroot -cursor_name left_ptr &

# Load defaults and resources
xrdb -load  ~/.Xdefaults &
xrdb -merge ~/.Xresources &
xrdb -merge ~/.config/Xdefaults/Xdefaults.theme.3024NIGHT

# Keybindings 
xmodmap ~/.xmodmap

# CAPS to CTRL
setxkbmap -option "ctrl:nocaps" -layout us -variant euro &

# Faster keyboard
xset r rate 300 50

gsynaptics-init

# Screensaver 
mate-screensaver &

# Start visual tools
random_wallpaper.sh $HOME/.wallpapers &
#$HOME/.scripts/__openbox_restart_dzen2.sh &
#$HOME/.scripts/__openbox_restart_tint2.sh &
#$HOME/.scripts/__openbox_restart_conky.sh &

# Set wmname for java applications
wmname "LG3D"

# Enable redshift 
redshift -l 52.37:4.89 &

# Start xmonad
exec dbus-launch --sh-syntax --exit-with-session xmonad

#exec dbus-launch --sh-syntax --exit-with-session openbox
