#export TERM=xterm-256color

# Locale
export LC_ALL=en_US.UTF-8

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin:~/.scripts:~/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -load  ~/.Xdefaults &
xrdb -merge ~/.Xresources &
xmodmap ~/.xmodmap
setxkbmap -option "ctrl:nocaps" -layout us -variant euro &

# Set a wallpaper
feh --bg-fill ~/.wallpapers/current &

# lightweight OSD notifications
#dunst &

# Tint2
#tint2 &

# Compton window fx
compton -b

# Set wmname for java applications redraw
wmname ATOM

# Enable redshift
redshift -l 52.37:4.89 &

# Start xmonad
exec dbus-launch --sh-syntax --exit-with-session xmonad
#exec dbus-launch --sh-syntax --exit-with-session openbox
